<?php

namespace ContainerGyslyYp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CoSERKqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CoSERKq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CoSERKq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', '.errored.3v04fF2', NULL, 'Cannot determine controller argument for "App\\Controller\\NpcController::showPlayers()": the $id argument is type-hinted with the non-existent class or interface: "App\\Controller\\id". Did you forget to add a use statement?'],
        ], [
            'id' => '?',
        ]);
    }
}
