<?php

namespace ContainerGyslyYp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConditionRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ConditionRepository' shared autowired service.
     *
     * @return \App\Repository\ConditionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ConditionRepository.php';

        return $container->privates['App\\Repository\\ConditionRepository'] = new \App\Repository\ConditionRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
