<?php

namespace ContainerGyslyYp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ImageRepository' shared autowired service.
     *
     * @return \App\Repository\ImageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ImageRepository.php';

        return $container->privates['App\\Repository\\ImageRepository'] = new \App\Repository\ImageRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
