<?php

namespace ContainerGyslyYp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.83t1iHB.App\Entity\Item' shared service.
     *
     * @return \App\Entity\Item
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.83t1iHB": it references class "App\\Entity\\Item" but no such service exists.');
    }
}
