<?php

namespace ContainerGyslyYp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicDashboardRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PublicDashboardRepository' shared autowired service.
     *
     * @return \App\Repository\PublicDashboardRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/PublicDashboardRepository.php';

        return $container->privates['App\\Repository\\PublicDashboardRepository'] = new \App\Repository\PublicDashboardRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
