<?php

namespace Container9ZStSEB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_3v04fF2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.3v04fF2' shared service.
     *
     * @return \App\Controller\id
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\NpcController::showPlayers()": the $id argument is type-hinted with the non-existent class or interface: "App\\Controller\\id". Did you forget to add a use statement?');
    }
}
