<?php

namespace ContainerII91HSa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BwK8duMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BwK8duM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BwK8duM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'creature' => ['privates', '.errored..service_locator.BwK8duM.App\\Entity\\Creature', NULL, 'Cannot autowire service ".service_locator.BwK8duM": it references class "App\\Entity\\Creature" but no such service exists.'],
        ], [
            'creature' => 'App\\Entity\\Creature',
        ]);
    }
}
