<?php

namespace Container58MKztK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QgUGWNmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QgUGWNm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QgUGWNm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'npc' => ['privates', '.errored..service_locator.QgUGWNm.App\\Entity\\Npc', NULL, 'Cannot autowire service ".service_locator.QgUGWNm": it references class "App\\Entity\\Npc" but no such service exists.'],
        ], [
            'npc' => 'App\\Entity\\Npc',
        ]);
    }
}
