<?php

namespace ContainerDn4mnS5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FIVGE_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fIVG_E.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fIVG_E.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'characterRepository' => ['privates', 'App\\Repository\\CharacterRepository', 'getCharacterRepositoryService', false],
        ], [
            'characterRepository' => 'App\\Repository\\CharacterRepository',
        ]);
    }
}
