<?php

namespace ContainerDn4mnS5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rib71KfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rib71Kf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rib71Kf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itemRepository' => ['privates', 'App\\Repository\\ItemRepository', 'getItemRepositoryService', false],
        ], [
            'itemRepository' => 'App\\Repository\\ItemRepository',
        ]);
    }
}
