<?php

namespace ContainerDn4mnS5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JbhBKvuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jbhBKvu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jbhBKvu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dash' => ['privates', '.errored..service_locator.jbhBKvu.App\\Entity\\Dash', NULL, 'Cannot autowire service ".service_locator.jbhBKvu": it references class "App\\Entity\\Dash" but no such service exists.'],
        ], [
            'dash' => 'App\\Entity\\Dash',
        ]);
    }
}
