<?php

namespace ContainerDn4mnS5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MR1eFScService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mR1eFSc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mR1eFSc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'location' => ['privates', '.errored..service_locator.mR1eFSc.App\\Entity\\Location', NULL, 'Cannot autowire service ".service_locator.mR1eFSc": it references class "App\\Entity\\Location" but no such service exists.'],
        ], [
            'location' => 'App\\Entity\\Location',
        ]);
    }
}
