<?php

namespace ContainerDn4mnS5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCharacter3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ky7FcZF.App\Entity\Character' shared service.
     *
     * @return \App\Entity\Character
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ky7FcZF": it references class "App\\Entity\\Character" but no such service exists.');
    }
}
