<?php

namespace ContainerLypjwq3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AOQT9XiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aOQT9Xi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aOQT9Xi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dashRepository' => ['privates', 'App\\Repository\\DashRepository', 'getDashRepositoryService', false],
        ], [
            'dashRepository' => 'App\\Repository\\DashRepository',
        ]);
    }
}
