<?php

namespace ContainerLypjwq3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ky7FcZFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ky7FcZF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ky7FcZF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'character' => ['privates', '.errored..service_locator.ky7FcZF.App\\Entity\\Character', NULL, 'Cannot autowire service ".service_locator.ky7FcZF": it references class "App\\Entity\\Character" but no such service exists.'],
            'request' => ['privates', '.errored.FlNwVdN', NULL, 'Cannot determine controller argument for "App\\Controller\\CharacterController::delete()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'character' => 'App\\Entity\\Character',
            'request' => '?',
        ]);
    }
}
