<?php

namespace ContainerLypjwq3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DHTCF9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DHT_cF9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DHT_cF9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encounterRepository' => ['privates', 'App\\Repository\\EncounterRepository', 'getEncounterRepositoryService', true],
        ], [
            'encounterRepository' => 'App\\Repository\\EncounterRepository',
        ]);
    }
}
