<?php

namespace ContainerLypjwq3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J_Obi3qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J.Obi3q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J.Obi3q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'otherRepository' => ['privates', 'App\\Repository\\OtherRepository', 'getOtherRepositoryService', false],
        ], [
            'otherRepository' => 'App\\Repository\\OtherRepository',
        ]);
    }
}
