<?php

namespace ContainerLypjwq3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HByM23cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hByM23c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hByM23c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encounter' => ['privates', '.errored..service_locator.hByM23c.App\\Entity\\Encounter', NULL, 'Cannot autowire service ".service_locator.hByM23c": it references class "App\\Entity\\Encounter" but no such service exists.'],
        ], [
            'encounter' => 'App\\Entity\\Encounter',
        ]);
    }
}
