<?php

namespace ContainerLypjwq3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNpcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QgUGWNm.App\Entity\Npc' shared service.
     *
     * @return \App\Entity\Npc
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QgUGWNm": it references class "App\\Entity\\Npc" but no such service exists.');
    }
}
