<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container58MKztK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container58MKztK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container58MKztK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container58MKztK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container58MKztK\App_KernelDevDebugContainer([
    'container.build_hash' => '58MKztK',
    'container.build_id' => '11f885df',
    'container.build_time' => 1628214355,
], __DIR__.\DIRECTORY_SEPARATOR.'Container58MKztK');
