<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIrp60uT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIrp60uT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIrp60uT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIrp60uT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIrp60uT\App_KernelDevDebugContainer([
    'container.build_hash' => 'Irp60uT',
    'container.build_id' => '8f5ba380',
    'container.build_time' => 1628094005,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIrp60uT');
