<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLypjwq3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLypjwq3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLypjwq3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLypjwq3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLypjwq3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lypjwq3',
    'container.build_id' => '043fa31a',
    'container.build_time' => 1629752262,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLypjwq3');
