<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.5897008e.js',
                '/build/608.ada1b953.js',
                '/build/app.a96099c7.js',
            ],
            'css' => [
                '/build/608.2c2ace24.css',
                '/build/app.665889d1.css',
            ],
        ],
    ],
],

]];
