<?php

namespace ContainerIrp60uT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__SchpoMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..schpoM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..schpoM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'other' => ['privates', '.errored..service_locator..schpoM.App\\Entity\\Other', NULL, 'Cannot autowire service ".service_locator..schpoM": it references class "App\\Entity\\Other" but no such service exists.'],
        ], [
            'other' => 'App\\Entity\\Other',
        ]);
    }
}
