<?php

namespace ContainerIrp60uT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOtherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..schpoM.App\Entity\Other' shared service.
     *
     * @return \App\Entity\Other
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..schpoM": it references class "App\\Entity\\Other" but no such service exists.');
    }
}
